### ISSUE TITLE
It is not clear how ChangedPasswordValidatePage should be used

### ISSUE THREAD

**Issue by SchnWalter** [devgateway/dg-toolkit#64]
Accessing the MountPath directly throws this error:

```
Last cause: Class org.apache.wicket.session.DefaultPageFactory can not access a member of class org.devgateway.toolkit.forms.wicket.page.user.ChangedPasswordValidatePage with modifiers ""
WicketMessage: Can't instantiate page using constructor 'org.devgateway.toolkit.forms.wicket.page.user.ChangedPasswordValidatePage(org.apache.wicket.request.mapper.parameter.PageParameters)' and argument ''. An exception has been thrown during construction!
```

**Comment by ionutdobre** [comment]
I believe it was used to validate user's emails in IMS; Check ```sendEmailToEnable``` method from ```SendEmailService``` class.

The confusion is determined by the ```changedPassword``` property from ```Person``` class that was used for something different than what the name suggests.

**Comment by ionutdobre** [comment]
Since ```ChangedPasswordValidatePage``` was created for a specific use in IMS I will remove this class from dg-toolkit.
