### ISSUE TITLE
React is minified in development mode on prod environments

### ISSUE THREAD

**Issue by mpostelnicu** [devgateway/dg-toolkit#70]
index.min.js:1 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

**Comment by mpostelnicu** [comment]
@alexeisavca any updates here ? let me know how do you plan to implement this, i think this production parameter should be automatically placed whenever build is executed through maven, because that is generally supposed to bake a release. you are using node to work locally, no ?

**Comment by alexeisavca** [comment]
Fixed
