### ISSUE TITLE
Select2 choice misbehaves when clicking on clear button

### ISSUE THREAD

**Issue by developster** [devgateway/dg-toolkit#83]
Now if I click on clear button it will clear the selection and at the same time will open selection. It shouldn't open it. Also while opening the select2 choice will move to top left corner.

Also may be related to this issue is that you cannot easily enter values with keyboard only. Try pressing tab and reach a select2 component then type something.. nothing happens, to let it capture input you must first press space.

**Comment by mpostelnicu** [comment]
will test to see if adding the css here https://fk.github.io/select2-bootstrap-css/ fixes the problem. we used to have this in IMS and never had issues.

**Comment by mpostelnicu** [comment]
it seems we now are using Select2 4.0.1 (part of wicketstuff-7.4.0) so the link above to fix the css no longer works. Need to use this one https://github.com/select2/select2-bootstrap-theme which is Less only, will compile it l8r and give it a try.
