### ISSUE TITLE
Backport the oc-explorer excel charts generators into dg-toolkit

### ISSUE THREAD

**Issue by mpostelnicu** [devgateway/dg-toolkit#87]
These features implemented by @ionutdobre are handy as part of a template project, they allow programmatic generation of excel charts within excel (without using the lame "images" technique, so these are real excel objects). Could be useful on any project that needs excel export with charts attached.

see https://github.com/devgateway/oc-explorer/tree/develop/web/src/main/java/org/devgateway/ocds/web/excelcharts

**Comment by ionutdobre** [comment]
I added the excel chart generator to dg-toolkit including some unit tests.
